#!/bin/sh
### BEGIN INIT INFO
# Provides:          garagebot
# Required-Start:    $remote_fs $syslog mysql
# Required-Stop:     $remote_fs $syslog mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# To install:
# cp garagebot_init /etc/init.d/garagebot
# chmod +x /etc/init.d/garagebot
# update-rc.d garagebot defaults

dir="/home/garagebot/garagebot"
cmd="$dir/garagebot"
user="root"

name=`basename $0`
pid_file="/var/run/$name.pid"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"

        if [ ! -d "$dir" ]; then
            echo "Directory $dir does not exist"
            exit 1
        fi

        if [ "$(id -u)" -ne 0 ]; then
            echo "Must be root to start $name"
            exit 1
        fi

        if [ -z "$user" ]; then
            echo "No user configured for $name"
            exit 1
        fi

        start-stop-daemon --start --make-pidfile --pidfile "$pid_file" --background --chdir "$dir" --chuid "$user" --exec "$cmd"
        if ! is_running; then
            echo "Unable to start"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
